package llm

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/abdessama-cto/ccb/internal/analyzer"
)

// AgentProposal describes a Claude Code subagent suggested by the LLM.
type AgentProposal struct {
	ID          string `json:"id"`
	Filename    string `json:"filename"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Reason      string `json:"reason"`
	Selected    bool   `json:"selected"`
}

// RuleProposal describes a project-specific rule suggested by the LLM.
type RuleProposal struct {
	ID       string `json:"id"`
	Rule     string `json:"rule"`
	Reason   string `json:"reason"`
	Selected bool   `json:"selected"`
}

// SkillProposal describes a Claude Code skill suggested by the LLM, or added
// interactively from the skills.sh catalog.
type SkillProposal struct {
	ID          string `json:"id"`
	Filename    string `json:"filename"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Reason      string `json:"reason"`
	Selected    bool   `json:"selected"`

	// When non-empty, the skill came from skills.sh — content must be fetched
	// from ExternalRawURL instead of being generated by the LLM.
	ExternalID     string `json:"-"` // skills.sh id, e.g. "supabase/agent-skills/supabase-postgres-best-practices"
	ExternalSource string `json:"-"` // e.g. "supabase/agent-skills"
}

// Proposals is the full set of LLM suggestions for the project.
type Proposals struct {
	Agents []AgentProposal `json:"agents"`
	Rules  []RuleProposal  `json:"rules"`
	Skills []SkillProposal `json:"skills"`
}

// GenerateProposals asks the LLM to propose agents, rules, and skills,
// using the project understanding, the fingerprint, and the wizard answers.
func GenerateProposals(cfg Config, u *ProjectUnderstanding, fp *analyzer.ProjectFingerprint, answers []WizardAnswer) (*Proposals, error) {
	prompt := buildProposalsPrompt(u, fp, answers) + "\n\n" + LanguageDirective(cfg)
	raw, err := CallLLM(cfg, prompt)
	if err != nil {
		return nil, err
	}
	return parseProposals(raw)
}

func buildProposalsPrompt(u *ProjectUnderstanding, fp *analyzer.ProjectFingerprint, answers []WizardAnswer) string {
	var sb strings.Builder
	sb.WriteString(`You are configuring Claude Code for a specific project.
Propose the agents, rules, and skills that would genuinely help an engineer
working on THIS codebase.

PHILOSOPHY:
- Quality over quantity. One sharp, obviously-useful proposal beats three vague ones.
- Ground every proposal in a real signal from the project — a file, a pattern,
  a domain detail, a wizard answer. If you can't justify it concretely, don't
  propose it.
- Avoid defensive filler agents like "code-reviewer", "debugger", "security-reviewer"
  unless the project has a specific domain (payments, auth, multi-tenant, etc.)
  that makes one genuinely useful.
- Rules are GUIDANCE, not commandments. Phrase them as "When X, here's how this
  project does Y" — avoid "NEVER", "ALWAYS", "MUST".

SIZING — scale proposals to project size:
`)
	sb.WriteString(proposalSizingHint(fp))
	sb.WriteString(`

FORMAT:
- Filenames: lowercase kebab-case, .md extension (e.g. "payment-webhook-guard.md").
- "selected" = true means the item is enabled by default.
- Every "reason" should cite the concrete signal you used (file path, pattern, domain).

Hard limits (cap, NOT a target): up to 6 agents, up to 8 rules, up to 8 skills.

Return ONLY this JSON (no markdown fences, no preamble):
{
  "agents": [
    {
      "id": "snake_case_id",
      "filename": "kebab-case.md",
      "name": "kebab-case-name",
      "description": "one-line description of what the agent does and when to invoke it",
      "reason": "why this specific agent for THIS project — cite code/domain signals",
      "selected": true
    }
  ],
  "rules": [
    {
      "id": "snake_case_id",
      "rule": "the rule text as it should appear in the rules file",
      "reason": "why this rule for THIS project",
      "selected": true
    }
  ],
  "skills": [
    {
      "id": "snake_case_id",
      "filename": "kebab-case.md",
      "name": "kebab-case-name",
      "description": "what the skill teaches Claude to do",
      "reason": "why this skill for THIS project",
      "selected": true
    }
  ]
}

`)

	sb.WriteString("## Project understanding\n")
	if b, err := json.MarshalIndent(u, "", "  "); err == nil {
		sb.Write(b)
		sb.WriteString("\n\n")
	}

	sb.WriteString("## Static fingerprint\n")
	sb.WriteString(fmt.Sprintf("Stack: %s\n", fp.StackString()))
	sb.WriteString(fmt.Sprintf("Language: %s\nTests: %s\n", fp.Language, fp.TestFrameworksString()))
	sb.WriteString(fmt.Sprintf("CI: %v · Docker: %v · .env: %v\n\n", fp.HasCI, fp.HasDocker, fp.HasEnvFile))

	if len(answers) > 0 {
		sb.WriteString("## Wizard answers (engineer's intent)\n")
		for _, a := range answers {
			sb.WriteString(fmt.Sprintf("- [%s] %s → %q\n", a.ID, a.Question, a.Value))
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

func parseProposals(raw string) (*Proposals, error) {
	raw = StripJSONFences(raw)

	var p Proposals
	if err := json.Unmarshal([]byte(raw), &p); err != nil {
		preview := raw
		if len(preview) > 300 {
			preview = preview[:300]
		}
		return nil, fmt.Errorf("proposals JSON parse failed: %w (raw: %s)", err, preview)
	}

	// Sanity-cap
	if len(p.Agents) > 12 {
		p.Agents = p.Agents[:12]
	}
	if len(p.Rules) > 20 {
		p.Rules = p.Rules[:20]
	}
	if len(p.Skills) > 15 {
		p.Skills = p.Skills[:15]
	}

	// Ensure filenames end in .md
	for i := range p.Agents {
		p.Agents[i].Filename = ensureMD(p.Agents[i].Filename, p.Agents[i].Name)
	}
	for i := range p.Skills {
		p.Skills[i].Filename = ensureMD(p.Skills[i].Filename, p.Skills[i].Name)
	}

	return &p, nil
}

// proposalSizingHint returns a size-adaptive recommendation for how many
// agents/rules/skills to propose. The LLM treats "up to N" as a target unless
// we explicitly tell it otherwise — so we give concrete numbers per size tier.
func proposalSizingHint(fp *analyzer.ProjectFingerprint) string {
	switch {
	case fp.LOC < 3_000:
		return "- Project size: small (~" + locLabel(fp.LOC) + ").\n" +
			"  Aim for 1-3 agents, 2-4 rules, 2-4 skills. Fewer is fine if you can't justify more."
	case fp.LOC < 20_000:
		return "- Project size: mid (~" + locLabel(fp.LOC) + ").\n" +
			"  Aim for 2-4 agents, 3-6 rules, 3-6 skills."
	default:
		return "- Project size: large (~" + locLabel(fp.LOC) + ").\n" +
			"  Aim for 3-5 agents, 4-7 rules, 4-7 skills. Still prioritize signal over volume."
	}
}

func locLabel(loc int) string {
	if loc >= 1000 {
		return fmt.Sprintf("%dk LOC", loc/1000)
	}
	return fmt.Sprintf("%d LOC", loc)
}

func ensureMD(filename, fallback string) string {
	f := strings.TrimSpace(filename)
	if f == "" {
		f = fallback
	}
	f = strings.ToLower(strings.ReplaceAll(f, " ", "-"))
	if !strings.HasSuffix(f, ".md") {
		f += ".md"
	}
	return f
}
